Repository philniko/group_15-SOEN341_Project_F24, pull requests merged in 2024-09, with the labels that each got.

#9 feature: create project structure
  .gitignore
  client/.gitignore
  client/.vite/deps/_metadata.json
  client/.vite/deps/package.json
  client/README.md
  client/eslint.config.js
  client/index.html
  client/package-lock.json
  client/package.json
  client/public/vite.svg
  client/src/App.tsx
  client/src/main.tsx
  client/src/vite-env.d.ts
  client/tsconfig.app.json
  client/tsconfig.json
  client/tsconfig.node.json
  client/vite.config.ts
  server/index.js
  server/package-lock.json
  server/package.json
Labels: enhancement

#19 added instructions for usage in README
  README.md
Labels: documentation, sprint 1

#20 create Register page
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/Register.tsx
Labels: enhancement, sprint 1

#18 Feature/create backend for login
  server/index.js
  server/models/User.js
Labels: enhancement, sprint 1

#29 feature: implement password hashing
  server/index.js
  server/package-lock.json
  server/package.json
Labels: bug, enhancement, sprint 1

#31 Added group model and some refactoring
  server/index.js
  server/models/Group.js
  server/models/User.js
Labels: enhancement, sprint 1

#32 bugfix: register issue
  server/index.js
Labels: bug, sprint 1

#34 bugfix: server crash when email exists
  server/index.js
Labels: bug, sprint 1
