Repository philniko/group_15-SOEN341_Project_F24, pull requests merged in 2024-11, with the labels that each got.

#100 bugfix: rate yourself
  client/src/StudentDashboard/StudentGroup.tsx
Labels: bug, Sprint 3

#109 Feature/remove student
  client/src/InstructorDashboard/Group.tsx
  server/index.js
Labels: enhancement, Sprint 3

#106 Created Summary View
  client/src/App.tsx
  client/src/InstructorDashboard/Navbar.tsx
  client/src/InstructorDashboard/SummaryView.tsx
  server/index.js
Labels: enhancement, Sprint 3

#111 created student grade view
  client/src/StudentDashboard/StudentGroup.tsx
  server/index.js
Labels: enhancement, Sprint 3

#113 feature/group-name-change
  client/src/InstructorDashboard/Home.tsx
  client/src/InstructorDashboard/InstructorDashboard.css
  server/index.js
Labels: enhancement, Sprint 3

#114 bugfix/remove-student-button
  client/src/InstructorDashboard/Group.tsx
Labels: bug, Sprint 3

#118 Added Sprint 3 Meeting Minutes
  Meeting Minutes/Sprint 3/Group15_Sprint3_6_Oct30.txt
  Meeting Minutes/Sprint 3/Group15_Sprint3_7_Nov6.txt
Labels: documentation, Sprint 3

#124 feat: add group tabs to summary page grid
  client/src/InstructorDashboard/InstructorDashboard.css
  client/src/InstructorDashboard/Navbar.css
  client/src/InstructorDashboard/SummaryView.tsx
Labels: enhancement, Sprint 3

#126 117 us unit testing sprint 1 2
  .github/workflows/node.js.yml
  client/package-lock.json
  client/package.json
  client/src/setupTests.ts
  client/tests/InstructorDashboard/Group.test.tsx
  client/tests/Login.test.tsx
  client/tests/Register.test.tsx
  client/tsconfig.json
  client/vite.config.ts
  server/jest.config.js
  server/package-lock.json
  server/package.json
Labels: Sprint 3, UT

#128 feat: database creation script
  README.md
  server/database-creation/dbcreation.js
  server/database-creation/instructors.json
  server/database-creation/students.json
  server/package-lock.json
  server/package.json
Labels: enhancement, Sprint 3

#127 feat: detailed view
  client/src/App.tsx
  client/src/InstructorDashboard/DetailedView.css
  client/src/InstructorDashboard/DetailedView.tsx
  client/src/InstructorDashboard/Group.tsx
  client/src/InstructorDashboard/Navbar.css
  client/src/InstructorDashboard/Navbar.tsx
  client/src/Navbar/Navbar.css
  client/src/Navbar/Navbar.tsx
  client/src/StudentDashboard/Navbar.css
  client/src/StudentDashboard/Navbar.tsx
  server/index.js
Labels: enhancement, Sprint 3

#131 feat: show overall grade
  client/src/InstructorDashboard/Group.tsx
  server/database-creation/dbcreation.js
  server/index.js
Labels: enhancement, Sprint 3

#133 fix: db creation script students shouldn't rate themselves
  server/database-creation/dbcreation.js
  server/database-creation/students.json
Labels: enhancement, Sprint 3

#135 bugfix: db creation script bug
  server/database-creation/dbcreation.js
Labels: bug, Sprint 3

#136 docs: add work log file
  worklogs.txt
Labels: bug

#141 docs: worklog for Phil
  WorkLogs/philippenikolov.txt
  server/database-creation/dbcreation.js
  server/index.js
Labels: documentation, Sprint 4

#151 Task-Add Course To Group Schema
  server/models/Group.js
Labels: enhancement, Sprint 4, Task

#149 Feature/create chat
  client/package-lock.json
  client/package.json
  client/src/StudentDashboard/StudentDashboard.css
  client/src/StudentDashboard/StudentGroup.tsx
  server/index.js
  server/models/Group.js
  server/models/User.js
  server/package-lock.json
  server/package.json
Labels: enhancement, Sprint 4

#156 feat: private messaging
  client/package-lock.json
  client/package.json
  client/src/ChatSidebar/ChatSidebar.css
  client/src/ChatSidebar/ChatSidebar.tsx
  client/src/Navbar/Navbar.css
  client/src/Navbar/Navbar.tsx
  server/index.js
  server/models/Message.js
Labels: enhancement, Sprint 4

#155 Task-course server getter setters
  server/index.js
  server/models/Course.js
  server/models/Group.js
Labels: enhancement, Sprint 4, Task

#163 Task-Improve styling for group chat
  client/src/StudentDashboard/StudentDashboard.css
  client/src/StudentDashboard/StudentGroup.tsx
  server/models/Group.js
Labels: enhancement

#168 docs: Phil worklog
  WorkLogs/philippenikolov.txt
Labels: documentation, Sprint 4
