Repository philniko/group_15-SOEN341_Project_F24, pull requests merged in 2024-10, with the labels that each got.

#30 feature: teams management
  server/index.js
  server/models/Group.js
Labels: enhancement, sprint 1

#43 feat: jwt authentication and group creation
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/Login.tsx
  client/src/StudentDashboard/MyGroup.tsx
  server/index.js
  server/package-lock.json
  server/package.json
Labels: enhancement, Sprint 2

#63 Feature/create instructor group frontend component
  client/src/App.tsx
  client/src/InstructorDashboard/Group.tsx
  client/src/InstructorDashboard/Home.tsx
  client/src/InstructorDashboard/InstructorDashboard.css
  client/src/Login.tsx
  server/index.js
Labels: enhancement, Sprint 2

#65 feat: logout and protected routes
  client/src/App.tsx
  client/src/InstructorDashboard/Navbar.tsx
  client/src/StudentDashboard/Navbar.tsx
Labels: enhancement, Sprint 2

#67 bugfix: undefined username in navbar
  client/src/InstructorDashboard/Navbar.tsx
  server/index.js
Labels: bug, Sprint 2

#71 Feature/add user feedback
  client/src/InstructorDashboard/Group.tsx
  client/src/InstructorDashboard/Home.tsx
  client/src/Login.tsx
  client/src/Register.tsx
  server/index.js
Labels: enhancement, Sprint 2

#73 Feature/create student rating interface
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/InstructorDashboard/Group.tsx
  client/src/InstructorDashboard/Navbar.tsx
  client/src/StudentDashboard/Home.tsx
  client/src/StudentDashboard/StudentDashboard.css
  client/src/StudentDashboard/StudentGroup.tsx
  server/index.js
  server/models/Group.js
  server/models/Ratings.js
  server/models/User.js
Labels: enhancement, Sprint 2

#85 bugfix: undefined in navbar and protected routes issue
  client/src/App.tsx
  client/src/InstructorDashboard/Group.tsx
  client/src/InstructorDashboard/Home.tsx
  client/src/Login.tsx
  client/src/Register.tsx
  client/src/StudentDashboard/Home.tsx
  client/src/StudentDashboard/Navbar.tsx
  client/src/StudentDashboard/StudentGroup.tsx
Labels: bug

#87 bugfix: current ratings not reflected in ui
  client/src/StudentDashboard/StudentGroup.tsx
  server/index.js
  server/models/Ratings.js
Labels: bug

#88 docs: update readme
  README.md
Labels: documentation, Sprint 3
